In [2]:
from numpy import *

In [3]:
# 一维数组
v = array([1, 2, 3, 4])
# 二维数组
m = array([[12, 23], [34, 45]])
# 二维复数数组
b = array([[1, 2], [3, 4]], dtype=complex)

In [4]:
v, type(v), v.shape, v.size, v.dtype

(array([1, 2, 3, 4]), numpy.ndarray, (4,), 4, dtype('int64'))

In [6]:

m, type(m), m.shape, m.size, m.dtype

(array([[12, 23],
        [34, 45]]), numpy.ndarray, (2, 2), 4, dtype('int64'))

In [8]:
b, type(b), b.shape, b.size, b.dtype

(array([[ 1.+0.j,  2.+0.j],
        [ 3.+0.j,  4.+0.j]]), numpy.ndarray, (2, 2), 4, dtype('complex128'))

In [9]:
# 创建一维数组，   相当于range(0,10)
x = arange(0, 10, 1)
# 创建一维数组，相当于range(-1, 1, 0.1)
y = arange(-1, 1, 0.1)

In [11]:
x, y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
         -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
         -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
         -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
          2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
          5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
          8.00000000e-01,   9.00000000e-01]))

In [12]:
# 生成一维数组，元素有25个， 【0，10】平均
z = linspace(0, 10, 25)
# 生成一维数据，
z_e = logspace(0, 10, 10, base=e)

In [27]:
x, y = mgrid[0:5, 0:5]

In [13]:
# 生成随机数shape为(5,5)
random.rand(5, 5)

array([[ 0.44394184,  0.45494694,  0.50885206,  0.65728749,  0.02165723],
       [ 0.73611572,  0.79426919,  0.35117838,  0.40557183,  0.57072362],
       [ 0.94627869,  0.18477728,  0.1581807 ,  0.7146146 ,  0.49893056],
       [ 0.39594131,  0.89999685,  0.60236277,  0.1729313 ,  0.11008426],
       [ 0.2707    ,  0.89349834,  0.87711144,  0.1343805 ,  0.37003443]])

In [14]:
# 生成对角矩阵，矩阵的对角为该数组中的元素
diag([1]*10)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [15]:
diag([1, 2, 3], k=-2)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0]])

In [16]:
zeros((3,3))

In [17]:
ones((3, 4))


In [38]:
x = array([1, '2'])
x = array([None, 1, '2'])

In [41]:
list(x)

[None, 1, '2']

In [42]:
x = arange(0, 10, 0.5)
mask = (5 < x) + (x < 7.5)
x[mask]

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [48]:
indices = where(mask)

In [20]:
a = array([1, 1, 1, 1])
b = random.randint(0, 100, 12).reshape(3, 4)
print b

In [25]:
s = 'abcdefg'
fromstring(s, dtype=int8)

array([ 97,  98,  99, 100, 101, 102, 103], dtype=int8)

In [27]:
def func(i):
    return i % 4 + 1

fromfunction(func, (10, ))


array([ 1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  1.,  2.])