In [1]:
import tensorflow as tf

In [3]:
sess = tf.Session()

In [12]:
print(sess.run(tf.div(3, 4)))
print(sess.run(tf.truediv(3, 4)))
print(sess.run(tf.floordiv(3.0, 4.0)))
print(sess.run(tf.mod(22.0, 5.0)))
print(sess.run(tf.mod(22, 5)))
print(sess.run(tf.mod(22.0, 5)))
print(sess.run(tf.mod(22, 5)))

0
0.75
0.0
2.0
2
2.0
2


In [13]:
print(sess.run(tf.cross([1., 0, 0], [0, 1., 0])))

[ 0.  0.  1.]


In [16]:
import numpy as np

x_vals = np.array([1., 3., 5., 7., 9.])
x_data = tf.placeholder(tf.float32)
m_const = tf.constant(3.)
my_product = tf.multiply(x_data, m_const)
for x_val in x_vals:
    print(sess.run(my_product, feed_dict={x_data: x_val}))

3.0
9.0
15.0
21.0
27.0


In [20]:
my_arrays = np.array([[1., 3., 5., 7., 9.],
                      [-2., 0., 2., 4., 6.],
                      [-6., -3., 0., 3., 6.]])
x_vals = np.array([my_arrays, my_arrays + 1])

x_data = tf.placeholder(tf.float32, shape=(3, 5))

m1 = tf.constant([[1.], [0.], [-1.], [2.], [4.]])
m2 = tf.constant([[2.]])
a1 = tf.constant([[10.]])

prod1 = tf.matmul(x_data, m1)
prod2 = tf.matmul(prod1, m2)
add1 = tf.add(prod2, a1)

for x_val in x_vals:
    print(x_val)
    print(sess.run(prod1, feed_dict={x_data: x_val}))
    print(sess.run(add1, feed_dict={x_data: x_val}))


[[ 1.  3.  5.  7.  9.]
 [-2.  0.  2.  4.  6.]
 [-6. -3.  0.  3.  6.]]
[[ 46.]
 [ 28.]
 [ 24.]]
[[ 102.]
 [  66.]
 [  58.]]
[[  2.   4.   6.   8.  10.]
 [ -1.   1.   3.   5.   7.]
 [ -5.  -2.   1.   4.   7.]]
[[ 52.]
 [ 34.]
 [ 30.]]
[[ 114.]
 [  78.]
 [  70.]]


In [21]:
x_shape = [1, 4, 4, 1]
x_val = np.random.uniform(size=x_shape)

x_data = tf.placeholder(tf.float32, shape=x_shape)

my_filter = tf.constant(0.25, shape=[2, 2, 1, 1])
my_strides = [1, 2, 2, 1]
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides, padding='SAME''', name='Moving_Avg_Window')


def custom_layer(input_matrix):
    input_matrix_sqeezed = tf.squeeze(input_matrix)
    A = tf.constant([[1., 2.], [-1., 3.]])
    b = tf.constant(1., shape=[2, 2])
    temp1 = tf.matmul(A, input_matrix_sqeezed)
    temp = tf.add(temp1, b)
    return tf.sigmoid(temp)


with tf.name_scope('Custom_layer') as scope:
    custom_layer1 = custom_layer(mov_avg_layer)
    print(sess.run(custom_layer1, feed_dict={x_data: x_val}))


[[ 0.92461473  0.91808361]
 [ 0.88576722  0.87027287]]
